### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by boborbt** [ml-unito/DeepWordLearning#1]
At the following line:

https://github.com/ml-unito/DeepWordLearning/blob/12c9acb8fcd594f21b5e8e14a6aff5336edb64d6/RepresentationExperiments/collapse_representations.py#L10

```x_temp``` contains, at each element, the "difference" between two time steps in the original ```x```. Shouldn't we take the norm of the vectors representing the time steps then? It appears to me that you are just averaging their content which is unlikely to be what we want.

Am I missing something?

Rob

**Comment by Pibborn** [comment]
I am not sure what you mean by "take the norm of the vectors representing the time steps" - my understanding of what we want to do is in fact to average the activations which do not differ "enough". What am I missing here?

A possibly unrelated fix is in commit [457c157](https://github.com/ml-unito/DeepWordLearning/commit/457c157550fa4be0956279d09e68132d87db4f82). Is this what you meant? Either way, this was definitely a bug.

**Comment by boborbt** [comment]
To my recollection (and at the best of my understanding): we want to average the values of those vectors that are similar and consecutive in the sequence. The distance between the average of their contents is not a good similarity measure: you would end up to consider vector [1,0,0] and [0,0,1] as being similar just because they have the same proportions of 1s and 0s.

To me the criterion to decide if two vectors are to be collapsed is if ```norm(x[i] - x[i+1]) < threshold$. Does it make sense?

**Comment by Pibborn** [comment]
It absolutely does. Latest commit in the `issue1` branch should fix this issue. Do you agree?

**Comment by boborbt** [comment]
Yes. It seems right to me now.
