### ISSUE TITLE
Possible Bug 2

### ISSUE THREAD

**Issue by boborbt** [ml-unito/DeepWordLearning#2]
Shouldn't this:

https://github.com/ml-unito/DeepWordLearning/blob/12c9acb8fcd594f21b5e8e14a6aff5336edb64d6/RepresentationExperiments/collapse_representations.py#L22

be 

```
   avg_activation = 0
```

btw, just for the sake of clarity I would set:

```
  avg_activation = np.zeros(NUM_FEATURES)
```

just because it makes it clearer that avg_activations will be a vector and does not rely on the fact that the first time ```avg_activation += x[i]``` works on different types than all other times.

**Comment by boborbt** [comment]
While we are on that: ```avg_i``` might it better named ```count``` or something like this since it will not represent something related to ```i``` nor it represents an average...

**Comment by Pibborn** [comment]
[This commit](https://github.com/ml-unito/DeepWordLearning/commit/ba17c9b351cebea943b6cd7d335f40e2a8acb81e) tries to address all these concerns. Does it look OK to you?

**Comment by boborbt** [comment]
I commented one line that still looks odd to me...

**Comment by Pibborn** [comment]
Alright, should be fixed with [this one](https://github.com/ml-unito/DeepWordLearning/commit/73678cf1f8a6a8b7ef94ece7a9a72916b57c3c1d).
